--1EXEC sp_columns LMS_BOOK_DETAILS;--2SELECT * FROM LMS_FINE_DETAILS--3SELECT MEMBER_NAME FROM LMS_MEMBERS WHERE CITY = 'chennai';--4SELECT MEMBER_ID, MEMBER_NAME,CITY,MEMBERSHIP_STATUS FROM LMS_MEMBERS WHERE MEMBERSHIP_STATUS='Permanent'--5 SELECT M.MEMBER_ID,M.MEMBER_NAME FROM LMS_MEMBERS M , LMS_BOOK_ISSUE B WHERE M.MEMBER_ID=B.MEMBER_ID AND B.BOOK_CODE='BL000002' --6 SELECT BOOK_CODE,BOOK_TITLE,AUTHOR FROM LMS_BOOK_DETAILS WHERE AUTHOR LIKE 'P%'; --7 SELECT COUNT(*)  AS NO_OF_BOOKS FROM LMS_BOOK_DETAILS WHERE CATEGORY = 'JAVA'; --8 SELECT CATEGORY,COUNT(CATEGORY) AS NO_OF_BOOKS FROM LMS_BOOK_DETAILS GROUP BY CATEGORY --9SELECT COUNT(*)  AS NO_OF_BOOKS FROM LMS_BOOK_DETAILS WHERE PUBLICATION = 'Prentice Hall';--10SELECT I.BOOK_CODE,B.BOOK_TITLE FROM LMS_BOOK_ISSUE I,LMS_BOOK_DETAILS B WHERE DATE_ISSUE='2012-04-01'AND B.BOOK_CODE = I.BOOK_CODE--11SELECT MEMBER_ID,MEMBER_NAME,DATE_REGISTER,DATE_EXPIRE FROM LMS_MEMBERS WHERE DATE_EXPIRE<'2013-04-01'--12SELECT MEMBER_ID,MEMBER_NAME,DATE_REGISTER,MEMBERSHIP_STATUS FROM LMS_MEMBERS WHERE DATE_REGISTER<'2012-03-01' AND MEMBERSHIP_STATUS='Temporary'--13SELECT member_id,MEMBER_NAME as name FROM LMS_MEMBERS WHERE CITY = 'chennai' or city ='Delhi';--14select CONCAT(BOOK_TITLE,AUTHOR) AS BOOK_TITLE_IS_WRITTEN_BY_AUTHOR FROM LMS_BOOK_DETAILS--15SELECT AVG(PRICE) AS AVERAGE_PRICE FROM LMS_BOOK_DETAILS WHERE CATEGORY='JAVA'--16
SELECT SUPPLIER_ID,SUPPLIER_NAME,EMAIL FROM LMS_SUPPLIERS_DETAILS WHERE EMAIL LIKE '%gmail%'

--17
SELECT SUPPLIER_ID,SUPPLIER_NAME,COALESCE(CONTACT,EMAIL,ADDRESS) AS CONTACTDETAILS  FROM LMS_SUPPLIERS_DETAILS--18select MEMBER_ID,(select MEMBER_NAME from LMS_MEMBERS where MEMBER_ID=t1.MEMBER_ID )as MEMBER_NAME,BOOK_CODE,(select BOOK_TITLE from LMS_BOOK_DETAILS where BOOK_CODE=t1.BOOK_CODE)as BOOK_TITLE from LMS_BOOK_ISSUE t1 --19 SELECT T1.MEMBER_ID,(SELECT MEMBER_NAME FROM LMS_MEMBERS WHERE MEMBER_ID=T1.MEMBER_ID)AS MEMBER_NAME,(SELECT T2.FINE_RANGE FROM LMS_MEMBERS WHERE MEMBER_ID=T1.MEMBER_ID)AS FINE_RANGE,(SELECT FINE_AMOUNT FROM LMS_FINE_DETAILS T2 WHERE FINE_RANGE= T1.FINE_RANGE)AS FINE_AMOUNT FROM LMS_BOOK_ISSUE T1 LEFT JOIN LMS_FINE_DETAILS T2 ON T1.FINE_RANGE = T2.FINE_RANGE WHERE T2.FINE_AMOUNT < 100 --20 SELECT BOOK_CODE,BOOK_TITLE,RACK_NUM FROM LMS_BOOK_DETAILS where RACK_NUM='A1' ORDER BY BOOK_TITLE ASC --21 SELECT T1.MEMBER_ID,MEMBER_NAME,DATE_REGISTER FROM LMS_MEMBERS T1 LEFT JOIN LMS_BOOK_ISSUE T2 ON T1.MEMBER_ID = T2.MEMBER_ID WHERE T2.MEMBER_ID IS NULL

 --22

 select t1.MEMBER_ID,t2.MEMBER_NAME from LMS_BOOK_ISSUE t1 join LMS_MEMBERS t2 on t1.MEMBER_ID=t2.MEMBER_ID where t1.DATE_RETURN>=t1.DATE_RETURNED and YEAR(t1.DATE_RETURNED)=2012

 --23
 select RACK_NUM,COUNT(book_code) as NO_OF_BOOKS from LMS_BOOK_DETAILS group by RACK_NUM

 --24

 Select BOOK_ISSUE_NO,MEMBER_NAME,DATE_REGISTER,DATE_EXPIRE,BOOK_TITLE,CATEGORY, PRICE, DATE_ISSUE,DATE_RETURN,DATE_RETURNED,(select FINE_AMOUNT from LMS_FINE_DETAILS f where i.FINE_RANGE= f.FINE_RANGE)as FINE_AMOUNT 
 from LMS_BOOK_ISSUE i,LMS_MEMBERS m,LMS_BOOK_DETAILS b where i.MEMBER_ID=m.MEMBER_ID and b.BOOK_CODE=i.BOOK_CODE

 --25
